[package]
name = "fmrad2db"
version = "0.2.64"
authors = ["kmcg3413@gmail.com"]

[dependencies.pcap]
[dependencies.byteorder]
[dependencies.toml]
[dependencies.ham]
path  = "/home/kmcguire/Projects/ham-rs/"
[dependencies.rand]
[dependencies.time]
