[package]
name = "fmrad2db"
version = "0.1.0"
authors = ["kmcguire"]

[dependencies.pcap]
[dependencies.byteorder]
[dependencies.toml]
[dependencies.ham]
git = "https://github.com/kmcguire3413/ham-rs"
[dependencies.rand]
[dependencies.time]
